name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: docker run -d -p 18830:1883 eclipse-mosquitto:2 mosquitto -c /mosquitto-no-auth.conf
      - run: pip install -r greemqtt/requirements.txt cryptography pytest pytest-asyncio
      - run: pytest -v
